spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/quiz_db
spring.datasource.username=coder2client
spring.datasource.password=pastoral2u

spring.jpa.hibernate.ddl-auto=update

# JWT settings (dev only ? override in prod via env)
app.jwt.secret=change_this_dev_secret_to_a_long_random_value_please
app.jwt.expiration-ms=86400000

# H2 console for local testing
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
