spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/quiz_db
spring.datasource.username=coder2client
spring.datasource.password=pastoral2u

spring.jpa.hibernate.ddl-auto=update
